"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.HOME_MODULE = exports.POLYGON_GET_MARKET_HOLIDAYS_MODULE = exports.POLYGON_GET_STOCK_SPLITS_MODULE = exports.POLYGON_GET_MARKET_STATUS_MODULE = exports.POLYGON_GET_FINANCIALS_MODULE = exports.POLYGON_GET_COMPANY_DETAILS_MODULE = exports.POLYGON_GET_NEWS_MODULE = exports.FINTEL_GET_OWNER_INFO_MODULE = exports.FINTEL_GET_STOCK_FILINGS_MODULE = exports.FINTEL_GET_STOCK_REG_FILINGS_MODULE = exports.FINTEL_GET_INSIDE_TRADES_MODULE = exports.FINTEL_GET_INSTITUTIONAL_HOLDINGS_MODULE = exports.FINTEL_GETS_SEC_SHORT_VOL_MODULE = exports.FINTEL_GET_SEC_OWNERSHIP_MODULE = exports.TD_GET_FUNDAMENTALS_MODULE = exports.TD_GET_MOVERS_MODULE = exports.TD_GET_PRICE_HISTORY_MODULE = exports.TD_GET_STOCK_MODULE = exports.FINTEL_GET_STOCK_FILINGS_ROUTE = exports.FINTEL_GET_OWNER_INFO_ROUTE = exports.FINTEL_GET_STOCK_REG_FILINGS_ROUTE = exports.FINTEL_GET_INSIDE_TRADES_ROUTE = exports.FINTEL_GET_INSTITUTIONAL_HOLDINGS_ROUTE = exports.FINTEL_GETS_SEC_SHORT_VOL_ROUTE = exports.FINTEL_GET_SEC_OWNERSHIP_ROUTE = exports.POLYGON_GET_MARKET_HOLIDAYS_ROUTE = exports.POLYGON_GET_STOCK_SPLITS_ROUTE = exports.POLYGON_GET_MARKET_STATUS_ROUTE = exports.POLYGON_GET_FINANCIALS_ROUTE = exports.POLYGON_GET_COMPANY_DETAILS_ROUTE = exports.POLYGON_GET_NEWS_ROUTE = exports.TD_GET_PRICE_HISTORY_ROUTE = exports.TD_GET_STOCK_ROUTE = exports.TD_GET_FUNDAMENTALS_ROUTE = exports.TD_GET_MOVERS_ROUTE = exports.POLYGON_API_KEY = exports.FINNHUB_API_KEY = exports.FINTEL_API_KEY = exports.TD_API_KEY = exports.setRoutes = exports.initialize = void 0;
var routes_1 = require("./routes");
Object.defineProperty(exports, "setRoutes", { enumerable: true, get: function () { return routes_1.setRoutes; } });
var initialize_1 = require("./initialize");
Object.defineProperty(exports, "initialize", { enumerable: true, get: function () { return initialize_1.initialize; } });
exports.TD_API_KEY = process.env.TD_API_KEY, exports.FINTEL_API_KEY = process.env.FINTEL_API_KEY, exports.FINNHUB_API_KEY = process.env.FINNHUB_API_KEY, exports.POLYGON_API_KEY = process.env.POLYGON_API_KEY;
exports.TD_GET_MOVERS_ROUTE = "/td-movers", exports.TD_GET_FUNDAMENTALS_ROUTE = "/td-fundamentals", exports.TD_GET_STOCK_ROUTE = "/td-stock", exports.TD_GET_PRICE_HISTORY_ROUTE = "/td-prices";
exports.POLYGON_GET_NEWS_ROUTE = "/poly-news", exports.POLYGON_GET_COMPANY_DETAILS_ROUTE = "/poly-company-details", exports.POLYGON_GET_FINANCIALS_ROUTE = "/poly-financials", exports.POLYGON_GET_MARKET_STATUS_ROUTE = "/poly-market-status", exports.POLYGON_GET_STOCK_SPLITS_ROUTE = "/poly-stock-splits", exports.POLYGON_GET_MARKET_HOLIDAYS_ROUTE = "/poly-market-holidays";
exports.FINTEL_GET_SEC_OWNERSHIP_ROUTE = "/fintel-sec-ownership", exports.FINTEL_GETS_SEC_SHORT_VOL_ROUTE = "/fintel-short-volume", exports.FINTEL_GET_INSTITUTIONAL_HOLDINGS_ROUTE = "/fintel-institutional-holdings", exports.FINTEL_GET_INSIDE_TRADES_ROUTE = "/fintel-inside-trades", exports.FINTEL_GET_STOCK_REG_FILINGS_ROUTE = "/fintel-stock-reg-filings", exports.FINTEL_GET_OWNER_INFO_ROUTE = "/fintel-owner-info", exports.FINTEL_GET_STOCK_FILINGS_ROUTE = "/fintel-stock-filings";
exports.TD_GET_STOCK_MODULE = require("./td/get-stock"), exports.TD_GET_PRICE_HISTORY_MODULE = require("./td/get-prices"), exports.TD_GET_MOVERS_MODULE = require("./td/get-movers"), exports.TD_GET_FUNDAMENTALS_MODULE = require("./td/get-fundamentals");
exports.FINTEL_GET_SEC_OWNERSHIP_MODULE = require("./fintel/get-sec-ownership"), exports.FINTEL_GETS_SEC_SHORT_VOL_MODULE = require("./fintel/get-sec-short-vol"), exports.FINTEL_GET_INSTITUTIONAL_HOLDINGS_MODULE = require("./fintel/get-institutional-holdings"), exports.FINTEL_GET_INSIDE_TRADES_MODULE = require("./fintel/get-inside-trades"), exports.FINTEL_GET_STOCK_REG_FILINGS_MODULE = require("./fintel/get-stock-reg-filings"), exports.FINTEL_GET_STOCK_FILINGS_MODULE = require("./fintel/get-stock-filings"), exports.FINTEL_GET_OWNER_INFO_MODULE = require("./fintel/get-owner-info");
exports.POLYGON_GET_NEWS_MODULE = require("./polygon/get-news"), exports.POLYGON_GET_COMPANY_DETAILS_MODULE = require("./polygon/get-company-details"), exports.POLYGON_GET_FINANCIALS_MODULE = require("./polygon/get-financials"), exports.POLYGON_GET_MARKET_STATUS_MODULE = require("./polygon/get-market-status"), exports.POLYGON_GET_STOCK_SPLITS_MODULE = require("./polygon/get-stock-splits"), exports.POLYGON_GET_MARKET_HOLIDAYS_MODULE = require("./polygon/get-market-holidays");
var home_1 = __importDefault(require("./home"));
exports.HOME_MODULE = home_1.default;
