import {
  TD_GET_FUNDAMENTALS_MODULE,
  TD_GET_MOVERS_MODULE,
  TD_GET_PRICE_HISTORY_MODULE,
  TD_GET_STOCK_MODULE,
  HOME_MODULE,
  POLYGON_GET_NEWS_MODULE,
  POLYGON_GET_COMPANY_DETAILS_MODULE,
  POLYGON_GET_FINANCIALS_MODULE,
  POLYGON_GET_MARKET_STATUS_MODULE,
  FINTEL_GETS_SEC_SHORT_VOL_MODULE,
  FINTEL_GET_STOCK_FILINGS_MODULE,
  FINTEL_GET_OWNER_INFO_MODULE,
  FINTEL_GET_SEC_OWNERSHIP_MODULE,
  FINTEL_GET_INSTITUTIONAL_HOLDINGS_MODULE,
  FINTEL_GET_INSIDE_TRADES_MODULE,
  FINTEL_GET_STOCK_REG_FILINGS_MODULE,
  POLYGON_GET_STOCK_SPLITS_MODULE,
  POLYGON_GET_MARKET_HOLIDAYS_MODULE,
  TD_GET_MOVERS_ROUTE,
  POLYGON_GET_COMPANY_DETAILS_ROUTE,
  POLYGON_GET_FINANCIALS_ROUTE,
  POLYGON_GET_MARKET_HOLIDAYS_ROUTE,
  POLYGON_GET_MARKET_STATUS_ROUTE,
  POLYGON_GET_NEWS_ROUTE,
  POLYGON_GET_STOCK_SPLITS_ROUTE,
  TD_GET_FUNDAMENTALS_ROUTE,
  TD_GET_STOCK_ROUTE,
  TD_GET_PRICE_HISTORY_ROUTE,
  FINTEL_GETS_SEC_SHORT_VOL_ROUTE,
  FINTEL_GET_INSTITUTIONAL_HOLDINGS_ROUTE,
  FINTEL_GET_SEC_OWNERSHIP_ROUTE,
  FINTEL_GET_STOCK_FILINGS_ROUTE,
  FINTEL_GET_INSIDE_TRADES_ROUTE,
  FINTEL_GET_OWNER_INFO_ROUTE,
  FINTEL_GET_STOCK_REG_FILINGS_ROUTE,
} from "./constants";

export function setRoutes(app: any) {
  app.get("/", HOME_MODULE);

  // TD FUNCTIONS
  app.get(TD_GET_MOVERS_ROUTE, TD_GET_MOVERS_MODULE);
  app.get(TD_GET_STOCK_ROUTE, TD_GET_STOCK_MODULE);
  app.get(TD_GET_FUNDAMENTALS_ROUTE, TD_GET_FUNDAMENTALS_MODULE);
  app.get(TD_GET_PRICE_HISTORY_ROUTE, TD_GET_PRICE_HISTORY_MODULE);
  app.get(POLYGON_GET_NEWS_ROUTE, POLYGON_GET_NEWS_MODULE);
  app.get(
    POLYGON_GET_COMPANY_DETAILS_ROUTE,
    POLYGON_GET_COMPANY_DETAILS_MODULE
  );
  app.get(POLYGON_GET_FINANCIALS_ROUTE, POLYGON_GET_FINANCIALS_MODULE);
  app.get(POLYGON_GET_MARKET_STATUS_ROUTE, POLYGON_GET_MARKET_STATUS_MODULE);
  app.get(POLYGON_GET_STOCK_SPLITS_ROUTE, POLYGON_GET_STOCK_SPLITS_MODULE);
  app.get(
    POLYGON_GET_MARKET_HOLIDAYS_ROUTE,
    POLYGON_GET_MARKET_HOLIDAYS_MODULE
  );
  app.get(FINTEL_GETS_SEC_SHORT_VOL_ROUTE, FINTEL_GETS_SEC_SHORT_VOL_MODULE);
  app.get(FINTEL_GET_STOCK_FILINGS_ROUTE, FINTEL_GET_STOCK_FILINGS_MODULE);
  app.get(FINTEL_GET_SEC_OWNERSHIP_ROUTE, FINTEL_GET_SEC_OWNERSHIP_MODULE);
  app.get(
    FINTEL_GET_INSTITUTIONAL_HOLDINGS_ROUTE,
    FINTEL_GET_INSTITUTIONAL_HOLDINGS_MODULE
  );
  app.get(FINTEL_GET_OWNER_INFO_ROUTE, FINTEL_GET_OWNER_INFO_MODULE);
  app.get(FINTEL_GET_INSIDE_TRADES_ROUTE, FINTEL_GET_INSIDE_TRADES_MODULE);
  app.get(
    FINTEL_GET_STOCK_REG_FILINGS_ROUTE,
    FINTEL_GET_STOCK_REG_FILINGS_MODULE
  );
}
